site_name: ZJUArtisan
site_url: https://github.com/ZJUArtisan/Archive/
site_description: ZJUArtisan
repo_name: ZJUArtisan/Archive
repo_url: https://github.com/ZJUArtisan/Archive/
edit_uri: tree/main/docs
copyright: Copyright &copy; 2024 ZJUArtisan

nav:
  - 主页:
    - index.md

theme:
  name: 'material'
  language: 'zh'
  icon:
    logo: material/notebook-outline
    repo: fontawesome/brands/github
    edit: material/pencil
  # favicon: https://zjuacee.blob.core.windows.net/zju-acee/icon.jpg
  custom_dir: overrides
  features:
  - content.code.annotate
  - content.action.edit
  - navigation.tracking
  - navigation.top
  - navigation.tabs
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  font:
    code: JetBrains Mono
  palette:
    - scheme: default
  
plugins:
  - search
  - toc
  - heti:
      extra_skipped_class:
        - arithmatex
  # - encryptcontent:
  #     title_prefix: ""
  #     summary: ''
  #     placeholder: '在此输入密码'
  #     encryption_info_message: '请输入密码'
  #     remember_password: True 
  #     default_expire_dalay: 48
  #     decryption_failure_message: '密码错误'
  #     global_password: 'ACEE2024'

  # - turing_changelog
  # - turing_contributors
  # - turing_evaluations
  # - turing_outdate_warning

extra_css:
  - https://fonts.googleapis.com/css?family=Noto+Serif+SC:300,300i,400,400i,700,700i&display=fallback
  - css/tasklist.css
  - css/card.css
  - css/custom.css

extra_javascript:
  - js/katex.js

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
